### PR TITLE
Need to align fuse-7.0.x branch.

### PR DESCRIPTION
**Pull request by cunningt**
Need to align fuse-7.0.x branch.

### CODE REVIEW

**Comment by jamesnetherton** [comment]
[merge]

**Comment by jamesnetherton** [comment]
[merge]

**Comment by cunningt** [comment]
[merge]

**Comment by cunningt** [comment]
[merge]

**Comment by cunningt** [comment]
[merge]

**Comment by cunningt** [comment]
[merge]

**Pull request merged**
